import type { Metadata } from "next";
import "../globals.css";
import ReactQueryProvider from "@/components/query-client-provider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "PCDACO Admin",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="container mx-auto h-screen">
      <ReactQueryProvider>{children}</ReactQueryProvider>
      <Toaster />
    </main>
  );
}
